import type { Metadata } from "next";
import { Montserrat, Merriweather, Source_Code_Pro, Pacifico } from "next/font/google";
import "./globals.css";

const montserratSans = Montserrat({
  variable: "--font-sans",
  subsets: ["latin"],
});

const sourceCodeProMono = Source_Code_Pro({
  variable: "--font-mono",
  subsets: ["latin"],
});

const merriweatherSerif = Merriweather({
  variable: "--font-serif",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  variable: "--font-pacifico",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratSans.variable} ${sourceCodeProMono.variable} ${merriweatherSerif.variable} ${pacifico.variable} antialiased`}
      >
        <main className="mx-auto">
        {children}
        </main>
       
      </body>
    </html>
  );
}
